services:
  app:
    build: .
    container_name: simulator
    volumes:
      - .:/go/src/
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true
    name: apache-kafka_default
